name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: go/src/github.com/domarx/patterns

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...
      env:
        GOPATH: /home/runner/work/patterns/go

    - name: Test
      run: go test -v ./...
      env:
        GOPATH: /home/runner/work/patterns/go
